### ISSUE TITLE
Scene service implementation

### ISSUE THREAD

**Issue by NelaMm** [robofit/arcor2_kinali#83] opened 2020-08-10 14:14 UTC
Can you please implement Scene service (by specification: https://gitlab.com/kinalisoft/test-it-off/scene) with creating configuration like Barcode or Search with KinaliSettings? 
Please can you divide method for calling to adding collisions by type of obejct (eg. box, mesh,...)?

**Comment by ZdenekM** [comment] 2020-08-11 07:32
The current state is somehow provisional - there will be (hopefully soon) Scene service 0.3.0 which will not have the Systems controller so this won't be needed (I believe). The Scene service is not an ordinary feature service - it is much more like Project service. It is integrated into the system, not something a user should add or configure.

What would be the point or advantage of dividing the method? In arcor2, there is a base object for collision models ```Model``` and collision models like ```Box``` or ```Sphere``` are derived from it. You can create whatever instance of collision object and pass it into the method, e.g.:

```python
scene_service.upsert_collision(Box("box_id", 0.1, 0.1, 0.1), Pose())
```
or
```python
scene_service.upsert_collision(Sphere("whatever_id", 0.1), Pose())
```

Is there something wrong with this approach? I think it is much simpler / elegant than having five or so separate functions.

**Comment by martincervinka** [comment] 2020-08-11 09:45
> The current state is somehow provisional

Yes, it is, but the basic rule, that client for any official (not alpha or beta) Feature service release has to provide full API functionality is still valid. We would like the client interface to be close to Web API as possible, but we do not insist on that. The exact form is up to you, but the full availability of the API is a must.

> there will be (hopefully soon) Scene service 0.3.0

Yes, should be soon but we are not sure when we can release Scene 0.2.0 with the final API for the first customer release.

> in which will not have the Systems controller so this won't be needed (I believe).

There will be a System controller, but with the different methods as mentioned in the proposal on Confluence.

**Comment by NelaMm** [comment] 2020-08-11 09:58
The division of methods would retain the form of api, but it is not necessary. However, we use the addition of Mesh, which is actually temporarily hacked.

**Comment by ZdenekM** [comment] 2020-08-12 05:51
@martincervinka We rely on what has been said - that Scene service will not have any configuration itself. The current state where Scene requires initialization with configuration ID is temporary. So if manual initialization through swagger is somehow problematic, you can easily work around it by adding the following code to your main script:

```python
from arcor2 import rest
scene_service_url = "http://url:port"
rest.put(f"http://{scene_service_url}/systems/ConfigurationId/create")
...
rest.put(f"http://{scene_service_url}/systems/destroy")
```

**Comment by ZdenekM** [comment] 2020-08-12 06:13
> However, we use the addition of Mesh, which is actually temporarily hacked.

Fixed by https://github.com/robofit/arcor2/pull/215.

**Comment by martincervinka** [comment] 2020-08-12 06:19
> We rely on what has been said - that Scene service will not have any configuration itself.

I don't think so, but this is pointless now. Let's discuss the proposal if you do not agree with that.

I understand you do not want to code something that will change, but as I said, we do not want to release something, that is based on a hacked, internally changed arcor2. Especially if the discussion about proposal can take more days. Milestone 0.3 release day is 21.8. Can you please fulfill our base requirement for python clients?

**Comment by ZdenekM** [comment] 2020-08-12 06:44
> > We rely on what has been said - that Scene service will not have any configuration itself.
> 
> I don't think so, but this is pointless now. Let's discuss the proposal if you do not agree with that.

I'm pretty sure that this has been stated - I asked about it several times during the last call :-) Is there any proposal for Scene 0.3.0? I do not know about any. We know about "Scene and project refactor proposal" and it states: 

> No Scene REST service URL present in scene.json - Scene service will be always present in system and its URL is loaded from environmental variable

Which we are fine with and we integrated Scene service into the arcor2 according to this.

> 
> I understand you do not want to code something that will change, but as I said, we do not want to release something, that is based on a hacked, internally changed arcor2. Especially if the discussion about proposal can take more days. Milestone 0.3 release day is 21.8. Can you please fulfill our base requirement for python clients?

The problem is that client for Scene service could not look exactly the same as clients for other feature services - it is an integral part of arcor2 so it can't depend on arcor2_kinali which depends on arcor2. Moreover, if scene service client requires initialization using configuration ID it would mean quite a complication for work with AREditor - we would ask the user for configuration ID probably and that would be quite a lot of (wasted) work.

There is nothing hacked or internally changed. I just proposed a workaround for this temporal state until it will be possible to implement everything in the proper way.

**Comment by ZdenekM** [comment] 2020-08-12 06:50
...of course, we could keep the client as it is and just add the proposed workaround (two methods) there (and ignore them in arcor2). It can be easily added in the same way into the main script where it is (as a temporal workaround) more appropriate - at least according to my opinion.

**Comment by martincervinka** [comment] 2020-08-12 06:53
> There is nothing hacked or internally changed. I just proposed a workaround for this temporal state until it will be possible to implement everything in the proper way.

I mean changed on our side. We do not want to use code, that is not versioned, released ... There is no proper way, there always be changes and after September or December I'm quite sure, there will be significant changes in APIs or even architecture. Currently, Scene is a classic Feature service, but yes essential as Robot was before ...

**Comment by ZdenekM** [comment] 2020-08-12 07:02
Just to avoid possible confusion - the proposed workaround is meant to be put into **the main script** - we do not propose hacking of arcor2 or arcor2_kinali...

**Closed as completed** 2020-09-03 13:38 UTC
